apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: streamlit-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8501
          env:
            - name: PROMETHEUS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: PROMETHEUS_URL
            - name: DEEPINFRA_MODEL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: DEEPINFRA_MODEL
            - name: DEEPINFRA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: DEEPINFRA_API_KEY