replicaCount: 1

image:
  repository: quay.io/rh-ee-lbitan/metric-mcp
  tag: test-linoy-multi-models2

service:
  type: ClusterIP
  port: 8000

route:
  enabled: true
  host: ai-metrics-summarizer.example.com

config:
  prometheusUrl: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"

llm:
  url: ""
  apiToken: ""
  modelName: ""

# List of available models for the UI dropdown - will be set by Makefile
availableModels: []

# Model mapping: model_id -> service_name - will be set by Makefile
modelMapping: {}
