replicaCount: 1

image:
  repository: quay.io/ecosystem-appeng/metric-ui
  tag: 0.45

service:
  type: ClusterIP
  port: 8501

route:
  enabled: true
  host: ai-metrics-summarizer.example.com

config:
  PROMETHEUS_URL: ""

llm:
  url: ""
  apiToken: ""

listModels:
  modelId:
    # Can be overridden via --set-json llamaStack.modelConfig.enabledModelIds='["model-id-1","model-id-2"]'
    enabledModelIds: []
