apiVersion: v1
kind: Service
metadata:
  name: preprocessor
spec:
  selector:
    app: preprocessor
  ports:
    - protocol: TCP
      port: {{ .Values.preprocessor.service.port }}
      targetPort: {{ .Values.preprocessor.service.port }}
