apiVersion: v1
kind: Service
metadata:
  name: summarizer
spec:
  selector:
    app: summarizer
  ports:
    - protocol: TCP
      port: {{ .Values.summarizer.service.port }}
      targetPort: {{ .Values.summarizer.service.port }}