kube-prometheus-stack:
  nameOverride: prometheus

  prometheus:
    name: vllm-prometheus
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 200m
      limits:
        memory: 2Gi
        cpu: 1
    storage:
      className: standard
      size: 50Gi
    retention: 15d
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      podMonitorSelector: {}
      podMonitorNamespaceSelector: {}

    service:
      name: prometheus
      type: ClusterIP
      port: 9090

    ingress:
      enabled: true
      ingressClassName: openshift-default
      hosts:
        - prometheus.apps-crc.testing
      paths:
        - /

  alertmanager:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: openshift-default
      hosts:
        - alertmanager.apps-crc.testing
      paths:
        - /
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

  grafana:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: openshift-default
      hosts:
        - grafana.apps-crc.testing
      paths:
        - /

    adminPassword: admin

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-operated:9090
            access: proxy
            isDefault: true

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ''
            type: file
            disableDeletion: true
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

  # OpenShift specific security context
  global:
    rbac:
      create: true
      pspEnabled: false
    
    securityContext:
      runAsUser: null
      runAsNonRoot: null
      fsGroup: null

  prometheusOperator:
    admissionWebhooks:
      enabled: false
    tls:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

route:
  name: prometheus
  tlsTermination: edge
  insecureEdgeTerminationPolicy: Redirect

rbac:
  serviceAccount:
    name: prometheus
  clusterRole:
    name: prometheus

serviceMonitor:
  name: vllm-metrics
  targetNamespace: redhat-vllm
  labels:
    app.kubernetes.io/name: vllm
  scrapeInterval: 15s
  endpoints:
    - port: metrics
      path: /metrics
    - port: model-metrics
      path: /model-metrics 